# Generated by Django 4.1.3 on 2023-01-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_form2_remove_form1_collage_remove_form1_document_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form1',
            new_name='new_form1',
        ),
        migrations.RenameModel(
            old_name='form2',
            new_name='new_form2',
        ),
        migrations.RenameModel(
            old_name='form3',
            new_name='new_form3',
        ),
    ]
