# Generated by Django 4.1.3 on 2023-01-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_form1_new_form1_rename_form2_new_form2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new_form3',
        ),
    ]
