# Generated by Django 4.1.3 on 2023-01-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_new_form3'),
    ]

    operations = [
        migrations.AddField(
            model_name='unaproved_employees',
            name='cheek',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
