# Generated by Django 4.1.3 on 2023-01-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department_Head', '0002_alter_dept_request_form2_employe_request_form1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept_request_form2',
            old_name='employe_request_form1',
            new_name='dept_request_form1',
        ),
    ]
