# Generated by Django 4.1.3 on 2023-01-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department_Head', '0003_rename_employe_request_form1_dept_request_form2_dept_request_form1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_request_form1_permanent',
            name='dept_head_Action',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=200, null=True),
        ),
    ]
