# Generated by Django 4.1.3 on 2023-01-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department_Head', '0004_alter_dept_request_form1_permanent_dept_head_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept_request_form1_permanent',
            name='note',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
