# Generated by Django 4.1.3 on 2023-01-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department_Head', '0006_dept_request_form1_permanent_recival_status_by_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_request_form1_permanent',
            name='Recival_status_by_Employer',
            field=models.CharField(choices=[('Received ', 'Received'), ('Not_Received ', 'Not_Received'), ('Returned', 'Returned')], max_length=200, null=True),
        ),
    ]
