# Generated by Django 4.1.3 on 2023-01-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department_Head', '0007_alter_dept_request_form1_permanent_recival_status_by_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept_request_form1_permanent',
            name='Serial_No',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dept_request_form1_permanent',
            name='Type_of_item',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dept_request_form1_permanent',
            name='Unique_Name_No',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
