# Generated by Django 4.1.3 on 2022-11-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catagory_Name', models.CharField(max_length=200, null=True)),
                ('Catagory_pic', models.ImageField(blank=True, null=True, upload_to='File/Catagory/')),
            ],
        ),
    ]
