# Generated by Django 4.1.3 on 2022-11-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0002_remove_catagory_catagory_pic_catagory_total_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='Catagory_Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='total_item',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
