# Generated by Django 4.1.3 on 2022-11-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0003_alter_catagory_catagory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='total_item',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
    ]
