# Generated by Django 4.1.3 on 2022-11-28 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0005_remove_catagory_total_item_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store_manager.catagory'),
        ),
    ]
