# Generated by Django 4.1.3 on 2022-11-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0010_remove_form2permanent_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form2permanent',
            old_name='form1',
            new_name='form1per',
        ),
    ]
