# Generated by Django 4.1.3 on 2022-11-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0011_rename_form1_form2permanent_form1per'),
    ]

    operations = [
        migrations.AddField(
            model_name='form2permanent',
            name='Status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepte', 'Accepte')], default='Pending', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='form2permanent',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
