# Generated by Django 4.1.3 on 2022-12-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0014_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_peopel',
            new_name='chat_peopel1',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_peopel2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
