# Generated by Django 4.1.3 on 2022-12-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0015_rename_chat_peopel_chat_chat_peopel1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_peopel2',
            new_name='_from',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='chat_peopel1',
            new_name='_to',
        ),
    ]
