# Generated by Django 4.1.3 on 2022-12-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0017_rename_chat_chatbot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='_to',
            new_name='_with',
        ),
        migrations.RenameField(
            model_name='chatbot',
            old_name='_from',
            new_name='me',
        ),
    ]
