# Generated by Django 4.1.3 on 2022-12-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0018_rename__to_chatbot__with_rename__from_chatbot_me'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='_with',
            new_name='me_with',
        ),
    ]
