# Generated by Django 4.1.3 on 2022-12-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0021_alter_chatbot_me_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='employ',
            name='Full_Name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='employ',
            name='about',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employ',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employ',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employ',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employ',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employ',
            name='phone1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employ',
            name='phone2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employ',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employ',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
