# Generated by Django 4.1.3 on 2022-12-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0022_employ_full_name_employ_about_employ_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employ',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
