# Generated by Django 4.1.3 on 2022-12-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0024_departments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
    ]
