# Generated by Django 4.1.3 on 2022-12-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0026_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorCode', models.CharField(max_length=300)),
                ('vendorName', models.CharField(max_length=300)),
                ('vendorProducts', models.CharField(max_length=300)),
                ('vendorOrigin', models.CharField(max_length=300)),
                ('vendorType', models.CharField(max_length=300)),
            ],
        ),
    ]
