# Generated by Django 4.1.3 on 2022-12-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0027_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='id',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendorCode',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
