# Generated by Django 4.1.3 on 2022-12-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0028_remove_vendor_id_alter_vendor_vendorcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendorAdded',
            field=models.DateField(auto_now=True),
        ),
    ]
