# Generated by Django 4.1.3 on 2022-12-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0032_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='roleMembers',
            field=models.IntegerField(),
        ),
    ]
