# Generated by Django 4.1.3 on 2022-12-14 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0033_alter_role_rolemembers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='role',
            new_name='allRole',
        ),
    ]
