# Generated by Django 4.1.3 on 2022-12-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0034_rename_role_allrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='allrole',
            name='roleDetails',
            field=models.TextField(blank=True, null=True),
        ),
    ]
