# Generated by Django 4.1.3 on 2022-12-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0035_allrole_roledetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(max_length=300)),
                ('storeDescription', models.TextField()),
                ('storeKeeper', models.CharField(max_length=300)),
                ('storeLocation', models.TextField()),
            ],
        ),
    ]
