# Generated by Django 4.1.3 on 2022-12-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0036_store'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='store',
            new_name='allStore',
        ),
    ]
