# Generated by Django 4.1.3 on 2022-12-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0037_rename_store_allstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store_manager.allstore'),
        ),
    ]
