# Generated by Django 4.1.3 on 2022-12-15 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0038_catagory_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employ',
            name='departments',
        ),
        migrations.AddField(
            model_name='employ',
            name='inDepartment',
            field=models.ForeignKey(max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store_manager.department'),
        ),
    ]
