# Generated by Django 4.1.3 on 2022-12-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0040_delete_student_employ_accessstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employ',
            name='role',
        ),
        migrations.AddField(
            model_name='employ',
            name='role',
            field=models.ManyToManyField(blank=True, to='Store_manager.allrole'),
        ),
    ]
