# Generated by Django 4.1.3 on 2022-12-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0041_remove_employ_role_employ_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employ',
            name='role',
        ),
        migrations.AddField(
            model_name='employ',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
