# Generated by Django 4.1.3 on 2022-12-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0043_item_action_item_approved_item_order_id_item_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='return_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
