# Generated by Django 4.1.3 on 2022-12-19 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0044_item_return_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store_manager.allstore'),
        ),
        migrations.AlterField(
            model_name='itemhistory',
            name='Reason',
            field=models.CharField(blank=True, choices=[('Returned Material', 'Returned Material'), ('Gift', 'Gift'), ('Purchased', 'Purchased'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
