# Generated by Django 4.1.3 on 2022-12-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0046_form1permanent_date_form1temp_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form2permanent',
            old_name='qty',
            new_name='reqqty',
        ),
        migrations.RenameField(
            model_name='form2temp',
            old_name='qty',
            new_name='req_qty',
        ),
        migrations.AddField(
            model_name='form2permanent',
            name='add_qty',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form2temp',
            name='add_qty',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
