# Generated by Django 4.1.3 on 2022-12-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0047_rename_qty_form2permanent_reqqty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form2permanent',
            old_name='reqqty',
            new_name='req_qty',
        ),
    ]
