# Generated by Django 4.1.3 on 2022-12-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0050_alter_form2permanent_add_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2permanent',
            name='add_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
