# Generated by Django 4.1.3 on 2022-12-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0051_alter_form2permanent_add_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2permanent',
            name='add_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
