# Generated by Django 4.1.3 on 2022-12-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0053_catagory_type_of_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='employe_request_form1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('Action', models.CharField(choices=[('Allowed', 'Allowed'), ('wait', 'wait'), ('Reject', 'Reject')], max_length=200, null=True)),
                ('Request_by', models.CharField(blank=True, max_length=100, null=True)),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('checkd_by', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('req_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('Remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
