# Generated by Django 4.1.3 on 2022-12-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0054_employe_request_form1'),
    ]

    operations = [
        migrations.AddField(
            model_name='employ',
            name='Thechnologist',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
