# Generated by Django 4.1.3 on 2022-12-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0055_employ_thechnologist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentHead',
            field=models.CharField(default='TBA', max_length=40, null=True),
        ),
    ]
