# Generated by Django 4.1.3 on 2022-12-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0056_alter_department_departmenthead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='inDepartment',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
