# Generated by Django 4.1.3 on 2023-01-02 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0057_alter_employ_indepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe_request_form1',
            name='checkd_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store_manager.employ'),
        ),
    ]
