# Generated by Django 4.1.3 on 2023-01-02 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0058_alter_employe_request_form1_checkd_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe_request_form1',
            old_name='Action',
            new_name='dept_head_Action',
        ),
        migrations.AddField(
            model_name='employe_request_form1',
            name='Store_Keeper_Action',
            field=models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employe_request_form1',
            name='request_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store_manager.allstore'),
        ),
    ]
