# Generated by Django 4.1.3 on 2023-01-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0060_remove_employe_request_form1_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe_request_form1',
            name='Store_Keeper_Action',
        ),
        migrations.RemoveField(
            model_name='employe_request_form1',
            name='dept_head_Action',
        ),
        migrations.CreateModel(
            name='employe_request_form2_permanent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('req_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('Remark', models.CharField(blank=True, max_length=100, null=True)),
                ('employe_request_form1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store_manager.employe_request_form1')),
            ],
        ),
        migrations.CreateModel(
            name='employe_request_form1_permanent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('dept_head_Action', models.CharField(choices=[('Allowed', 'Allowed'), ('wait', 'wait'), ('Reject', 'Reject')], max_length=200, null=True)),
                ('Store_Keeper_Action', models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject')], max_length=200, null=True)),
                ('Request_by', models.CharField(blank=True, max_length=100, null=True)),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('checkd_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store_manager.employ')),
                ('request_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store_manager.allstore')),
            ],
        ),
    ]
