# Generated by Django 4.1.3 on 2023-01-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0061_remove_employe_request_form1_store_keeper_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe_request_form2_permanent',
            name='employe_request_form1',
        ),
        migrations.AddField(
            model_name='employe_request_form2_permanent',
            name='employe_request_form1_permanent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store_manager.employe_request_form1_permanent'),
        ),
    ]
