# Generated by Django 4.1.3 on 2023-01-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0062_remove_employe_request_form2_permanent_employe_request_form1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe_request_form1_permanent',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employe_request_form1_permanent',
            name='Remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employe_request_form1_permanent',
            name='req_qty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employe_request_form1_permanent',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='employe_request_form2_permanent',
        ),
    ]
