# Generated by Django 4.1.3 on 2023-01-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0063_employe_request_form1_permanent_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe_request_form1_permanent',
            name='Store_Keeper_Action',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Reject', 'Reject')], max_length=200, null=True),
        ),
    ]
