# Generated by Django 4.1.3 on 2023-01-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0067_alter_employe_request_form1_permanent_dept_head_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe_request_form1_permanent',
            name='note',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
