# Generated by Django 4.1.3 on 2023-01-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0068_employe_request_form1_permanent_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe_request_form1_permanent',
            name='Store_Keeper_Action',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Allowed', 'Allowed'), ('wait', 'wait'), ('Reject', 'Reject'), ('Received ', 'Received')], default='Pending', max_length=200, null=True),
        ),
    ]
