# Generated by Django 4.1.3 on 2023-01-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0069_alter_employe_request_form1_permanent_store_keeper_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe_request_form1_permanent',
            name='Recival_status_by_Employer',
            field=models.CharField(choices=[('Received ', 'Received'), ('Not_Received ', 'Not_Received')], default='Not_Received', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employe_request_form1_permanent',
            name='Store_Keeper_Action',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Allowed', 'Allowed'), ('Reject', 'Reject'), ('Received ', 'Received')], default='Pending', max_length=200, null=True),
        ),
    ]
