# Generated by Django 4.1.3 on 2023-01-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0071_alter_employe_request_form1_permanent_recival_status_by_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employ',
            name='Collage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employ',
            name='Document',
            field=models.FileField(blank=True, null=True, upload_to='File/Document'),
        ),
        migrations.AddField(
            model_name='employ',
            name='Filed_Study',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employ',
            name='Titel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employ',
            name='Year_Graguation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employ',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
