# Generated by Django 4.1.3 on 2023-01-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0073_alter_employe_request_form1_permanent_recival_status_by_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemhistory',
            name='Approved',
        ),
        migrations.AlterField(
            model_name='itemhistory',
            name='Action',
            field=models.CharField(choices=[('Add', 'Add'), ('Removed', 'Removed')], max_length=200),
        ),
    ]
