# Generated by Django 4.1.3 on 2023-01-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0074_remove_itemhistory_approved_alter_itemhistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemhistory',
            name='Amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
