# Generated by Django 4.1.3 on 2023-01-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0078_itemhistory_return_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe_request_form1_permanent',
            name='Serial_No',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employe_request_form1_permanent',
            name='Type_of_item',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employe_request_form1_permanent',
            name='Unique_Name_No',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
