# Generated by Django 4.1.3 on 2023-01-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0080_itemhistory_taken_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form2permanent',
            name='Status',
        ),
        migrations.AddField(
            model_name='form2permanent',
            name='Admin_Appruval',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Reject', 'Reject')], default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='form2permanent',
            name='Finance_Action',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='form2permanent',
            name='Item_Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=200),
        ),
    ]
