# Generated by Django 4.1.3 on 2023-02-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store_manager', '0082_form2permanent_admin_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form2permanent',
            name='Finance_response',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
