# Generated by Django 4.1.3 on 2022-12-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Admin', '0005_departments1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Departments1',
        ),
    ]
