# Generated by Django 4.1.3 on 2022-12-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Admin', '0007_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
